'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
const db=supabase()
export default function Home(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState('')
 const [company,setCompany]=useState(null),[name,setName]=useState(''),[members,setMembers]=useState([]),[tasks,setTasks]=useState([]),[memberName,setMemberName]=useState(''),[taskTitle,setTaskTitle]=useState(''),[assigned,setAssigned]=useState(''),[target,setTarget]=useState('')
 useEffect(()=>{db.auth.getSession().then(({data})=>setSession(data.session));const {data:s}=db.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 async function load(){const uid=(await db.auth.getUser()).data.user?.id;if(!uid)return;let {data:c}=await db.from('companies').select('*').or(`created_by.eq.${uid}`).limit(1).maybeSingle();setCompany(c||null);if(c){let {data:m}=await db.from('company_members').select('*').eq('company_id',c.id).eq('active',true).order('created_at');setMembers(m||[]);let {data:t}=await db.from('tasks').select('*').eq('company_id',c.id).order('created_at',{ascending:false});setTasks(t||[])}}
 async function signup(){setMsg('');let {error}=await db.auth.signUp({email,password});setMsg(error?error.message:'Conta criada. Se o Supabase pedir confirmação, confirme o e-mail e entre.')}
 async function login(){setMsg('');let {error}=await db.auth.signInWithPassword({email,password});setMsg(error?error.message:'')}
 async function createCompany(){const u=(await db.auth.getUser()).data.user;let {data:c,error}=await db.from('companies').insert({name,created_by:u.id}).select().single();if(error)return setMsg(error.message);let {error:e}=await db.from('company_members').insert({company_id:c.id,user_id:u.id,name:u.email?.split('@')[0]||'Administrador',email:u.email,role:'admin'});if(e)return setMsg(e.message);setCompany(c);load()}
 async function addMember(){if(!memberName.trim())return;let {error}=await db.from('company_members').insert({company_id:company.id,name:memberName.trim(),role:'employee'});if(error)setMsg(error.message);else{setMemberName('');load()}}
 async function addTask(){if(!taskTitle.trim())return;let {error}=await db.from('tasks').insert({company_id:company.id,title:taskTitle.trim(),assigned_to:assigned||null,quantity_target:Number(target)||0,priority:'normal',status:'pending'});if(error)setMsg(error.message);else{setTaskTitle('');setTarget('');load()}}
 async function advance(t){const next=t.status==='pending'?'in_progress':t.status==='in_progress'?'completed':'pending';await db.from('tasks').update({status:next,quantity_done:next==='completed'?t.quantity_target:t.quantity_done,completed_at:next==='completed'?new Date().toISOString():null}).eq('id',t.id);load()}
 const stats=useMemo(()=>({pending:tasks.filter(x=>x.status==='pending').length,progress:tasks.filter(x=>x.status==='in_progress').length,done:tasks.filter(x=>x.status==='completed').length}),[tasks])
 if(!session)return <main className="center"><section className="login"><div className="brand">MG <b>Oper</b></div><h1>Organize o trabalho do dia.</h1><p>Entre para administrar sua empresa, equipe, metas e tarefas.</p><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)}/><div className="row"><button onClick={login}>Entrar</button><button className="ghost" onClick={signup}>Criar conta</button></div>{msg&&<small>{msg}</small>}</section></main>
 if(!company)return <main className="center"><section className="login"><div className="brand">MG <b>Oper</b></div><h1>Crie sua empresa</h1><p>Esse será seu espaço de trabalho.</p><input placeholder="Nome da empresa" value={name} onChange={e=>setName(e.target.value)}/><button onClick={createCompany}>Começar a usar</button>{msg&&<small>{msg}</small>}</section></main>
 return <div><header><div className="brand">MG <b>Oper</b></div><div><span>{company.name}</span><button className="link" onClick={()=>db.auth.signOut()}>Sair</button></div></header><main className="wrap"><section className="hero"><div><p className="eyebrow">PROGRAMAÇÃO DO DIA</p><h1>O que precisa ser feito hoje?</h1><p>Cadastre a equipe, distribua tarefas e acompanhe as metas.</p></div><button onClick={()=>window.print()}>Imprimir programação</button></section><section className="stats"><Card n={stats.pending} t="Pendentes"/><Card n={stats.progress} t="Em andamento"/><Card n={stats.done} t="Concluídas"/><Card n={members.length} t="Pessoas"/></section><section className="grid"><div className="panel"><h2>Nova tarefa</h2><input placeholder="Ex.: Separar pedidos da manhã" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/><select value={assigned} onChange={e=>setAssigned(e.target.value)}><option value="">Responsável</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input type="number" placeholder="Meta / quantidade" value={target} onChange={e=>setTarget(e.target.value)}/><button onClick={addTask}>Delegar tarefa</button><h2 className="mt">Equipe</h2><div className="inline"><input placeholder="Nome do funcionário" value={memberName} onChange={e=>setMemberName(e.target.value)}/><button onClick={addMember}>Adicionar</button></div><div className="chips">{members.map(m=><span key={m.id}>{m.name}</span>)}</div></div><div className="panel"><h2>Tarefas de hoje</h2>{tasks.length===0?<p className="muted">Nenhuma tarefa ainda. Cadastre a primeira ao lado.</p>:tasks.map(t=>{const m=members.find(x=>x.id===t.assigned_to);return <article className="task" key={t.id}><div><strong>{t.title}</strong><p>{m?.name||'Sem responsável'} {t.quantity_target>0?`• Meta: ${t.quantity_target}`:''}</p></div><button className={t.status} onClick={()=>advance(t)}>{t.status==='pending'?'Pendente':t.status==='in_progress'?'Em andamento':'Concluída'}</button></article>})}</div></section><section className="panel"><h2>Ocorrências rápidas</h2><div className="alerts"><span>📦 Falta de matéria-prima</span><span>🛠️ Equipamento parado</span><span>↩️ Retrabalho</span><span>⏱️ Atraso</span></div><p className="muted">Estrutura pronta no banco; a próxima versão liga o registro detalhado de ocorrências e ordens individuais de impressão.</p></section>{msg&&<div className="toast">{msg}</div>}</main></div>}
function Card({n,t}){return <div className="card"><b>{n}</b><span>{t}</span></div>}
